name: "Setup env"
description: "Install component for devenv and nx to work"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v26
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        aws-region: aws-region-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    #- name: Yarn install
    #  uses: nick-fields/retry@v3
    #  with:
    #    timeout_minutes: 10
    #    max_attempts: 3
    #    command: devenv shell yarn install
