name: E2E Test

on:
  push:
    branches:
      - codebuild
  pull_request:
    branches:
      - codebuild
  workflow_dispatch:

permissions: {}

jobs:
  docker:
    name: Docker E2E Tests
    runs-on: 
      - codebuild-github-demo-${{ github.run_id }}-${{ github.run_attempt }}
        buildspec-override:true
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Env"
        uses: ./.github/actions/setup-env
      - name: Compose up
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx compose:up ui
          sleep 60
      - name: Test
        shell: devenv shell bash -- -e {0}
        run: |
          CYPRESS_BASE_URL='http://localhost:8888' yarn nx execute e2e
      - name: Compose down
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx compose:down ui
